imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:         rotating_file
            path:         "%kernel.logs_dir%/%kernel.environment%.log"
            level:        debug
            channels:     [!app, !event, !doctrine]
            max_files:    10
        console:
            type:         console
            channels:     [!app, !event, !doctrine]
        app:
            type:         rotating_file
            path:         "%kernel.logs_dir%/app.log"
            level:        debug
            channels:     [app]
            max_files:    10
