# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '%admin_password%'
                        roles: 'ROLE_ADMIN'
                    privalia:
                        password: '%guest_password%'
                        roles: 'ROLE_GUEST'

    # Tell Symfony what algorithm was used to encode the passwords for the users
    # To create a password for the admin user try:
    # php bin/console security:encode-password
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    # The main job of a firewall is to configure how your users will authenticate:
    # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
    firewalls:

        # Disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Activate different ways to authenticate:
        # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
        main:
            anonymous: ~

            # Enable HTTP basic authentication (the old-school prompt)
            http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            # form_login: ~

            logout:
                path:   /logout
                target: /

    role_hierarchy:
        ROLE_ADMIN: ROLE_GUEST

    access_control:
        # require ROLE_ADMIN for /game/admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login$, roles: [ IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_REMEMBERED ] }
