# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    davamigo.http.client:
        class: Davamigo\HttpClient\CurlHttpClient\CurlHttpClient

    app.maze.builder:
        class: AppBundle\Domain\Service\MazeBuilder\MazeBuilderRecursiveDivision

    app.maze.renderer:
        class: AppBundle\Domain\Service\MazeRender\MazeIconRender

    app.game.engine:
        class: AppBundle\Domain\Service\GameEngine\GameEngine
        arguments:
            - "@app.game.move_players_async.service"
            - "@app.ghost.move.factory"
            - "@logger"
        public: true

    app.game.daemon:
        class: AppBundle\Service\GameEngine\GameDaemon
        public: true

    app.game.move_players_sync.service:
        class: AppBundle\Domain\Service\MovePlayer\MoveAllPlayersSyncService
        arguments:
            - "@app.player.move_sync.service"

    app.game.move_players_async.service:
        class: AppBundle\Service\MovePlayer\MoveAllPlayersAsyncService
        arguments:
            - "@rabbitmq.connection"
            - "@app.player.request_data"
            - "@app.player.move.service"

    app.player.validate.service:
        class: AppBundle\Domain\Service\MovePlayer\ValidatePlayerService
        arguments:
            - "@app.player.move.api"

    app.player.move.service:
        class: AppBundle\Domain\Service\MovePlayer\MovePlayerService

    app.player.move_sync.service:
        class: AppBundle\Domain\Service\MovePlayer\MovePlayerSyncDecoratorService
        arguments:
            - "@app.player.move.service"
            - "@app.player.request_data"
            - "@app.player.move.api"

    app.player.move.api:
        class: AppBundle\Service\MovePlayer\ApiPlayerService
        arguments:
            - "@davamigo.http.client"
            - "@validator"
            - "@app.logger"
            - "%default_timeout%"

    app.player.request_data:
        class: AppBundle\Domain\Service\MovePlayer\PlayerRequest

    app.ghost.move.factory:
        class: AppBundle\Domain\Service\MoveGhost\MoveGhostFactory
        arguments:
            - 1: "@app.ghost.move.random"
              2: "@app.ghost.move.killing"

    app.ghost.move.random:
        class: AppBundle\Domain\Service\MoveGhost\MoveGhostRandom

    app.ghost.move.killing:
        class: AppBundle\Domain\Service\MoveGhost\MoveGhostKilling

    app.logger:
        class: AppBundle\Service\LoggerService\LoggerService
        arguments:
            - "@doctrine.orm.entity_manager"

    rabbitmq.connection:
        class: PhpAmqpLib\Connection\AMQPStreamConnection
        arguments:
            - "%rabbitmq_host%"
            - "%rabbitmq_port%"
            - "%rabbitmq_user%"
            - "%rabbitmq_pass%"
            - "%rabbitmq_vhost%"
